name: Run Quality Report

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Run Quality Report
    runs-on: macos-14
    permissions:
      contents: write

    steps:
      - name: Add path globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # pin@v4
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Xcode select
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Build and Test
        run: |
          set -o pipefail && xcodebuild -scheme Networking-Package test \
           -destination "platform=macOS,arch=arm64,variant=Mac Catalyst" \
           -enableCodeCoverage YES \
           -resultBundlePath result.xcresult | xcbeautify
            
      - name: Run SonarCloud Scanning
        run: |
          bash xccov-to-sonarqube-generic.sh result.xcresult > sonarqube-generic-coverage.xml

          brew install sonar-scanner

          sonar-scanner \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.coverageReportPaths="sonarqube-generic-coverage.xml"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment Version
        id: versioning
        uses: Oliver-Binns/Versioning@4695fba9f63bed5b557094f9a64f7a2b1a7639e8 # pin@v1.1.0
        with:
          ACTION_TYPE: Release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
